version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: golangstore-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golang_store
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    container_name: golangstore-redis
    ports:
      - "6379:6379"
